### ISSUE TITLE
App crush after install

### ISSUE THREAD

**Issue by Staler2019** [quan0715/ncuber#3]
Description: As soon as I open the app, it crush.

Phone: Samsung A53
Phone Arch: android-arm64
Android SDK: 33
log:
```.txt
D/AndroidRuntime(24030): Shutting down VM
E/AndroidRuntime(24030): FATAL EXCEPTION: main
E/AndroidRuntime(24030): Process: com.example.ncuber, PID: 24030
E/AndroidRuntime(24030): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~T26ci1031R5ukPOoXWeyGw==/com.example.ncuber-dIW26YAN7NBB303ouFN1-A==/base.apk)
E/AndroidRuntime(24030): 	at com.lyokone.location.FlutterLocation.setActivity(FlutterLocation.java:109)
E/AndroidRuntime(24030): 	at com.lyokone.location.FlutterLocationService.setActivity(FlutterLocationService.kt:255)
E/AndroidRuntime(24030): 	at com.lyokone.location.LocationPlugin.dispose(LocationPlugin.java:121)
E/AndroidRuntime(24030): 	at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java:56)
E/AndroidRuntime(24030): 	at com.lyokone.location.LocationPlugin.onDetachedFromActivityForConfigChanges(LocationPlugin.java:74)
E/AndroidRuntime(24030): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivityForConfigChanges(FlutterEngineConnectionRegistry.java:367)
E/AndroidRuntime(24030): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:688)
E/AndroidRuntime(24030): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:762)
E/AndroidRuntime(24030): 	at android.app.Activity.performDestroy(Activity.java:8864)
E/AndroidRuntime(24030): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1419)
E/AndroidRuntime(24030): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6067)
E/AndroidRuntime(24030): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6113)
E/AndroidRuntime(24030): 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6460)
E/AndroidRuntime(24030): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6341)
E/AndroidRuntime(24030): 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
E/AndroidRuntime(24030): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(24030): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(24030): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(24030): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
E/AndroidRuntime(24030): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(24030): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(24030): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(24030): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(24030): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24030): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(24030): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
I/Process (24030): Sending signal. PID: 24030 SIG: 9
Lost connection to device.
Exited (sigterm)
```

**Comment by Staler2019** [comment]
Could probably solved by the following issue

https://github.com/Baseflow/flutter-geolocator/issues/1214#issuecomment-1419562502

**Comment by Staler2019** [comment]
solved
