### ISSUE TITLE
App throw "java.util.concurrent.ExecutionException" using "google_maps_flutter" package

### ISSUE THREAD

**Issue by Staler2019** [quan0715/ncuber#5]
Description: logcat shows that cannot access `google_map_sdk`

Phone: Samsung A53
Phone Arch: android-arm64
Android SDK: 33
logcat:
```.txt
I/DynamiteModule( 6892): Selected remote version of com.google.android.gms.googlecertificates, version >= 7
2
W/ziparchive( 6892): Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/00000005/GoogleCertificates.dm': No such file or directory
I/SnapshotHandler( 6892): Unable to retrieve flag snapshot for com.google.android.libraries.consentverifier#com.example.ncuber, using defaults.
W/MobStoreFlagStore( 6892): Unable to update local snapshot for com.google.android.libraries.consentverifier#com.example.ncuber, may result in stale flags.
W/MobStoreFlagStore( 6892): java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.example.ncuber, sha256=[2f605fc183b4edafbd303f0dbeb587b34ff660eab066ddab079da01a28e1f8bb], atk=true, ver=225014047.true (go/gsrlt)
W/MobStoreFlagStore( 6892): 	at ajg.s(:com.google.android.gms.dynamite_mapsdynamite@225014047@22.50.14 (190800-0):3)
W/MobStoreFlagStore( 6892): 	at ajg.get(:com.google.android.gms.dynamite_mapsdynamite@225014047@22.50.14 (190800-0):2)
W/MobStoreFlagStore( 6892): 	at akq.g(:com.google.android.gms.dynamite_mapsdynamite@225014047@22.50.14 (190800-0):2)
W/MobStoreFlagStore( 6892): 	at yo.d(:com.google.android.gms.dynamite_mapsdynamite@225014047@22.50.14 (190800-0):1)
W/MobStoreFlagStore( 6892): 	at yq.run(:com.google.android.gms.dynamite_mapsdynamite@225014047@22.50.14 (190800-0):0)
W/MobStoreFlagStore( 6892): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
W/MobStoreFlagStore( 6892): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
W/MobStoreFlagStore( 6892): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
W/MobStoreFlagStore( 6892): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/MobStoreFlagStore( 6892): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/MobStoreFlagStore( 6892): 	at java.lang.Thread.run(Thread.java:1012)
W/MobStoreFlagStore( 6892): Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.example.ncuber, sha256=[2f605fc183b4edafbd303f0dbeb587b34ff660eab066ddab079da01a28e1f8bb], atk=true, ver=225014047.true (go/gsrlt)
W/MobStoreFlagStore( 6892): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
W/MobStoreFlagStore( 6892): 	at android.os.Parcel.createException(Parcel.java:2995)
W/MobStoreFlagStore( 6892): 	at android.os.Parcel.readException(Parcel.java:2978)
W/MobStoreFlagStore( 6892): 	at android.os.Parcel.readException(Parcel.java:2920)
W/MobStoreFlagStore( 6892): 	at fc.c(:com.google.android.gms.dynamite_mapsdynamite@225014047@22.50.14 (190800-0):2)
W/MobStoreFlagStore( 6892): 	at rr.a(:com.google.android.gms.dynamite_mapsdynamite@225014047@22.50.14 (190800-0):4)
W/MobStoreFlagStore( 6892): 	at ji.e(:com.google.android.gms.dynamite_mapsdynamite@225014047@22.50.14 (190800-0):2)
W/MobStoreFlagStore( 6892): 	at kh.t(:com.google.android.gms.dynamite_mapsdynamite@225014047@22.50.14 (190800-0):2)
W/MobStoreFlagStore( 6892): 	at kh.u(:com.google.android.gms.dynamite_mapsdynamite@225014047@22.50.14 (190800-0):3)
W/MobStoreFlagStore( 6892): 	at kh.e(:com.google.android.gms.dynamite_mapsdynamite@225014047@22.50.14 (190800-0):2)
W/MobStoreFlagStore( 6892): 	at kl.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@225014047@22.50.14 (190800-0):69)
W/MobStoreFlagStore( 6892): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/MobStoreFlagStore( 6892): 	at android.os.Looper.loopOnce(Looper.java:201)
W/MobStoreFlagStore( 6892): 	at android.os.Looper.loop(Looper.java:288)
W/MobStoreFlagStore( 6892): 	at android.os.HandlerThread.run(HandlerThread.java:67)
D/CompatibilityChangeReporter( 6892): Compat change id reported: 150939131; UID 10159; state: ENABLED
Application finished.
Exited (sigterm)
```

**Comment by Staler2019** [comment]
@quan0715 幫我看一下這個有沒有打開

![image](https://github.com/quan0715/ncuber/assets/56055434/120513ec-0309-4b2a-9825-6b78b3989226)

https://github.com/flutter/flutter/issues/109115#issuecomment-1338779416

**Comment by quan0715** [comment]
<img width="787" alt="image" src="https://github.com/quan0715/ncuber/assets/60366187/a3ea65e6-7e54-4a9a-a00d-86e1a7f2943e">
我已經打開了 確實呼叫的流量近來

**Comment by Staler2019** [comment]
那可能他不是個 error XD
